Feature/jc 599 make a book catalog page with a new design
saritasa-nest/camp-js-2024-trinh-nguyen pull request #1
Opened 2024-07-05 02:55 UTC by trinhnguyen-saritasa

2024-07-05 10:23 UTC, irina-baleevskih-saritasa commented on apps/vanilla/src/pages/index.css
> +	position: absolute;
Let's use padding, you already set absolute position to button

2024-07-05 10:23 UTC, irina-baleevskih-saritasa commented on apps/vanilla/src/pages/index.css
> +	font-size: 14px;
You use vars for spacing, colors and also you set value. May be we can leave common approach ?

2024-07-05 10:23 UTC, irina-baleevskih-saritasa commented on apps/vanilla/src/pages/index.css
> +	outline: none !important;
We shouldn't hide the outline, also we should avoid !important

2024-07-05 10:23 UTC, irina-baleevskih-saritasa commented on apps/vanilla/src/pages/index.css
> +	--gradient: linear-gradient(
It's small component and Ithink this style is redundant

2024-07-05 10:23 UTC, irina-baleevskih-saritasa commented on apps/vanilla/src/pages/index.css
> +.filters__checkbox-wrapper input {
Let's use classes instead tags as selectors

2024-07-05 10:23 UTC, irina-baleevskih-saritasa commented on apps/vanilla/src/pages/index.css
> +	input[type="radio"]:checked::before {
I didn't find radio input, may be we can remove it?

2024-07-05 10:23 UTC, irina-baleevskih-saritasa commented on apps/vanilla/src/pages/index.html
> +          <div class="section__group">
Let's use ul to grouped data

2024-07-05 10:47 UTC, trinhnguyen-saritasa commented on apps/vanilla/src/pages/index.css
> +	top: 0;
I removed top: 0; it doesn't work any more. But I still use justify to keep the "Books app" center

2024-07-05 10:49 UTC, trinhnguyen-saritasa commented on apps/vanilla/src/pages/index.css
> +	height: 100vh;
yeah, margin and height does not work any more. I removed them. But I keep padding to make my work looks like the design in figma.

2024-07-05 10:51 UTC, irina-baleevskih-saritasa commented on apps/vanilla/src/pages/index.css
> +	top: 0;
Yes, it's correct, I mean only 'top' style

2024-07-05 11:15 UTC, timofei-maximov-saritasa requested changes

2024-07-05 11:15 UTC, timofei-maximov-saritasa commented on apps/vanilla/src/pages/index.html
> +    <hr class="sparate" />
Typo. Let's come up with a better name like: 
```suggestion
    <hr class="divider" />
```

2024-07-05 11:15 UTC, timofei-maximov-saritasa commented on apps/vanilla/src/pages/images/c.jpg
Do we need this?

2024-07-05 11:15 UTC, timofei-maximov-saritasa commented on apps/vanilla/src/pages/images/bookIcon.jpg
Same

2024-07-05 11:15 UTC, timofei-maximov-saritasa commented on apps/vanilla/src/pages/images/cleancode.jpg
Please, remove unused assets, even if they are cute :(

2024-07-05 11:15 UTC, timofei-maximov-saritasa commented on apps/vanilla/src/pages/index.css
> +	font-weight: lighter;
Font style doesn't match with what we have in design

2024-07-05 11:15 UTC, timofei-maximov-saritasa commented on apps/vanilla/src/pages/index.css
> +.sparate--disable {
Please, take a look at your divider. It doesn't match color with design

2024-07-05 11:15 UTC, timofei-maximov-saritasa commented on apps/vanilla/src/pages/index.html
> +              <p class="article__title">Master</p>
Don't forget to use the same titles as in design

2024-07-05 11:15 UTC, timofei-maximov-saritasa commented on apps/vanilla/src/pages/index.html
> +        <div>
You have duplicating `1980` section

2024-07-05 11:15 UTC, timofei-maximov-saritasa commented on apps/vanilla/src/pages/index.html
> +        <div>
It should be `section` to be semantically correct

2024-07-05 11:22 UTC, daoduong-saritasa requested changes
Please review all your usage of color, try not to use plain value such as `white`, consider create a variable for it for better maintainability.

2024-07-05 11:22 UTC, daoduong-saritasa commented on apps/vanilla/src/pages/index.css
> +	border-radius: 12px;
Same with variable for border, something like this should do:
`--border-radius: 12px`
`--border-radius-lg: 24px;`

2024-07-05 11:22 UTC, daoduong-saritasa commented on apps/vanilla/src/pages/index.css
> +	padding: var(--spacing-sm) var(--spacing-sm);
```suggestion
	padding: var(--spacing-sm);
```

2024-07-05 11:22 UTC, daoduong-saritasa commented on apps/vanilla/src/pages/index.css
> +.content__main__filter__checkbox__input {
Is this class used anywhere?

2024-07-05 11:22 UTC, daoduong-saritasa commented on apps/vanilla/src/pages/index.css
> +.content__footer__container {
Please review your class usage, I see this class doesn't get used anywhere. Should remove them.

2024-07-05 11:22 UTC, daoduong-saritasa commented on apps/vanilla/src/pages/index.css
> +	font-size: 1.35em;
Why this element have different size?

2024-07-05 11:22 UTC, daoduong-saritasa commented on apps/vanilla/src/pages/index.css
> +	border-raudis: 4px;
Typo

2024-07-05 11:22 UTC, daoduong-saritasa commented on apps/vanilla/src/pages/index.css
> +	margin-bottom: -0.125em;
For other styling different from `font-size` please consider using `px`

2024-07-05 11:22 UTC, daoduong-saritasa commented on apps/vanilla/src/pages/index.html
> +      <h5>📚 Books app</h5>
Why do we start with an `h5`? Review this https://arc.net/l/quote/mgytdsbh

2024-07-05 11:22 UTC, daoduong-saritasa commented on apps/vanilla/src/pages/index.html
> +    <hr class="sparate" />
```suggestion
    <hr class="separate" />
```

2024-07-05 11:22 UTC, daoduong-saritasa commented on apps/vanilla/src/pages/index.html
> +      <section class="section">
The class name does not have any meaning, this should identify what this section represent.

2024-07-05 11:22 UTC, daoduong-saritasa commented on apps/vanilla/src/pages/index.html
> +          <a>Github</a>
Remember to add `href` when using `a` tag, if it's not do anything, set it like this `href="#"`

2024-07-05 11:22 UTC, daoduong-saritasa commented on apps/vanilla/src/pages/index.html
> +      <hr class="sparate sparate--disable" />
```suggestion
      <hr class="sparate sparate--hide" />
```

2024-07-05 17:59 UTC, trinhnguyen-saritasa commented on apps/vanilla/src/pages/index.css
> +	--gradient: linear-gradient(
thank you. I removed them.

2024-07-05 18:05 UTC, trinhnguyen-saritasa commented on apps/vanilla/src/pages/index.html
> +      <h5>📚 Books app</h5>
Yeah, I changed it. Thank you.

2024-07-05 18:08 UTC, trinhnguyen-saritasa commented on apps/vanilla/src/pages/index.html
> +          <h5 class="section__year">1980 YEAR</h5>
I found it had sticky on mobile. Can you check it again? I set position: sticky;

2024-07-05 18:23 UTC, trinhnguyen-saritasa commented on apps/vanilla/src/global/variables.css
> +  --gap-medium: 10px;
I made mistake here, I should have used spacing instead. I removed  it.

2024-07-05 18:26 UTC, trinhnguyen-saritasa commented on apps/vanilla/src/pages/index.css
> +	font-weight: lighter;
Thank you. I fixed it.

2024-07-05 18:28 UTC, trinhnguyen-saritasa commented on apps/vanilla/src/pages/index.html
> +      <h5>📚 Books app</h5>
Yeah, I changed to h1 for the first main content.

2024-07-05 18:30 UTC, trinhnguyen-saritasa commented on apps/vanilla/src/pages/index.html
> +      <section class="section">
I changed it to divider (with other reviewers suggested) and I have just changed it color. So I kept it.

2024-07-05 18:30 UTC, trinhnguyen-saritasa commented on apps/vanilla/src/pages/index.html
> +      <hr class="sparate sparate--disable" />
Thank you

2024-07-05 18:37 UTC, trinhnguyen-saritasa commented on apps/vanilla/src/pages/images/c.jpg
No. I removed it. Thank you

2024-07-09 11:01 UTC, daoduong-saritasa approved these changes
Great job :+1:

2024-07-09 11:01 UTC, daoduong-saritasa commented on apps/vanilla/src/global/variables.css
> +	--second-color: #000;
```suggestion
--primary-color: #ffffff;
--second-color: #000000;
```

2024-07-10 04:59 UTC, timofei-maximov-saritasa reviewed
Please, review your css variables usage. You have a lot of colors used directly. Some of these colors don't match with what we have in figma.

2024-07-10 04:59 UTC, timofei-maximov-saritasa commented on apps/vanilla/src/pages/images/bookIcon.jpg
Do you need this image?

2024-07-10 04:59 UTC, timofei-maximov-saritasa commented on apps/vanilla/src/pages/index.css
> +	color: gray;
Let's use css variables for colors, I believe we have design token for this

2024-07-10 04:59 UTC, timofei-maximov-saritasa commented on apps/vanilla/src/pages/index.css
> +	background: #f0f0f0;
Same here, please check styles in figma for select

![image](https://github.com/saritasa-nest/camp-js-2024-trinh-nguyen/assets/86595911/8ea6acfc-eaf1-443f-a1e4-dcd07d71a808)

2024-07-10 04:59 UTC, timofei-maximov-saritasa commented on apps/vanilla/src/pages/index.css
> +	background-image: url("https://static.thenounproject.com/png/1666929-200.png");
This asset can be downloaded from figma

![image](https://github.com/saritasa-nest/camp-js-2024-trinh-nguyen/assets/86595911/f21f20eb-c575-4047-ac5f-3547048df28c)

2024-07-10 04:59 UTC, timofei-maximov-saritasa commented on apps/vanilla/src/pages/index.css
> +	color: #5a6674;
Same with css variables

2024-07-10 04:59 UTC, timofei-maximov-saritasa commented on apps/vanilla/src/pages/index.css
> +}
What do `first` and `second` mean from a naming perspective? It's not clear. Let's improve class naming

2024-07-10 04:59 UTC, timofei-maximov-saritasa commented on apps/vanilla/src/pages/index.css
> +	color: var(--divider-color);
Color is not applied on chrome.

You can try using `border-color` here. But check it on firefox if you are using it.

2024-07-11 11:27 UTC, trinhnguyen-saritasa commented on apps/vanilla/src/pages/images/bookIcon.jpg
I removed all non-usage images. Thank you sir.

2024-07-11 11:48 UTC, trinhnguyen-saritasa commented on apps/vanilla/src/pages/index.css
> +}
Yeah, thank you sir. I changed it.

2024-07-15 10:57 UTC, timofei-maximov-saritasa approved these changes

2024-07-15 10:57 UTC, timofei-maximov-saritasa commented on apps/vanilla/vite.config.ts
> -        resolve(root, 'example', 'nested', 'index.html'),
Don't forget to add `book-catalog` and `blackjack` pages here. 
This deleted code snippet was an example of adding multiple `html` files. Currently, preview is not working.

You can test it locally by running `npm run vanilla:build` and then running output locally.

2024-07-15 10:57 UTC, timofei-maximov-saritasa commented on apps/vanilla/src/pages/index.html
> +			<h1 >Main Page</h1>
```suggestion
			<h1>Main Page</h1>
```

2024-07-15 10:57 UTC, timofei-maximov-saritasa commented on apps/vanilla/src/pages/index.html
> +		<header >
```suggestion
		<header>
```

2024-07-15 10:57 UTC, timofei-maximov-saritasa commented on apps/vanilla/src/pages/index.html
> +			<h1 >
```suggestion
		<main>
			<h1>
```

2024-07-15 10:57 UTC, timofei-maximov-saritasa commented on apps/vanilla/src/pages/index.html
> +			<h1 >
```suggestion
			<h1>
```

2024-07-15 11:55 UTC, trinhnguyen-saritasa commented on apps/vanilla/vite.config.ts
> -        resolve(root, 'example', 'nested', 'index.html'),
thank you

2024-07-17 10:23 UTC, TienLuu-Saritasa approved these changes

2024-07-17 10:24 UTC, merged