Feature: Create black-jack game JC-625
saritasa-nest/camp-js-2024-trinh-nguyen pull request #2
Opened 2024-07-12 10:10 UTC by trinhnguyen-saritasa

I have created a Black-jack game to practice implementing observer design pattern. Thank you.

2024-07-13 06:12 UTC, khoanguyen-saritasa requested changes

2024-07-13 06:12 UTC, khoanguyen-saritasa commented on apps/vanilla/src/pages/black-jack/features/player-displayer.ts
> +		const newestScore = turnResult[turnResult.length - 1];
And, you can use at to get the latest element `turnResult.at(-1);`. But, you will need to check `null` case for this approach.

2024-07-13 06:12 UTC, khoanguyen-saritasa commented on apps/vanilla/src/pages/black-jack/features/player.ts
> +	private readonly diceResults: number[] = [];
Usually, when representing an array as `readonly`, you should add `readonly` to its type to prevent mutation actions, such as `push`. If you want to use methods like `push`, then remove `readonly` from the variable.

```suggestion
	private readonly diceResults: readonly number[] = [];
```

2024-07-13 06:12 UTC, khoanguyen-saritasa commented on apps/vanilla/src/pages/black-jack/models/player-turn-result.ts
> +/** StoreObject score and index. */
Can you improve the docs?

2024-07-13 06:12 UTC, khoanguyen-saritasa commented on apps/vanilla/src/pages/black-jack/models/publisher.ts
> +	/** */
? TODO :)

2024-07-13 06:12 UTC, khoanguyen-saritasa commented on apps/vanilla/src/type-guards/is-element.ts
> +}
When you add a type guard, you cannot guarantee the type of the element you are checking, so in this case, it should be `unknown`, not `HTMLElement | HTMLSpanElement | null | undefined`. BTW, can we use `element instanceof HTMLElement` for our checking condition, like you did with the button element?

2024-07-13 06:15 UTC, khoanguyen-saritasa commented on apps/vanilla/src/pages/black-jack/features/player-displayer.ts
> +export class PlayerDisplayer extends ResultDisplayer implements Subscriber<number[]> {
Why this class docs is `Display winner`? Is it expected?

2024-07-13 06:19 UTC, khoanguyen-saritasa commented
And also, seems like all the checks failed. Please fix them.

2024-07-13 07:22 UTC, trinhnguyen-saritasa commented on apps/vanilla/src/pages/black-jack/features/dice-generator.ts
> +	}
Yeah I fixed it. Thank you sir.

2024-07-13 07:35 UTC, trinhnguyen-saritasa commented on apps/vanilla/src/pages/black-jack/features/main.ts
> +			.fill(null)
The array created is to create Player object by default. Therefore, you suggest me to use Array.from instead of using Array(numberOfPlayer).fill(null) which it wastes time to create element null first, right?

2024-07-13 07:46 UTC, trinhnguyen-saritasa commented on apps/vanilla/src/pages/black-jack/features/player-displayer.ts
> +		const newestScore = turnResult[turnResult.length - 1];
Oh, I see. Using turnResult.at(-1) is faster. I changed it. Thank you.

2024-07-13 07:54 UTC, trinhnguyen-saritasa commented on apps/vanilla/src/pages/black-jack/features/player.ts
> +	private readonly diceResults: number[] = [];
I use readonly here: private readonly diceResults: number[] = []; as I just want diceResult array can not change its whole array but it can still push new element to array.

2024-07-13 07:56 UTC, trinhnguyen-saritasa commented on apps/vanilla/src/pages/black-jack/models/publisher.ts
> +	/** */
I am so sorry. I forgot to fix it. I add comment there. Thank you. :(

2024-07-13 07:59 UTC, trinhnguyen-saritasa commented on apps/vanilla/src/pages/black-jack/features/player-displayer.ts
> +export class PlayerDisplayer extends ResultDisplayer implements Subscriber<number[]> {
I fixed it. Thank you

2024-07-13 08:03 UTC, trinhnguyen-saritasa commented on apps/vanilla/src/type-guards/is-element.ts
> +}
Thank you. I changed it.

2024-07-13 08:19 UTC, khoanguyen-saritasa commented on apps/vanilla/src/pages/black-jack/features/main.ts
> +			.fill(null)
Yeah, when making an array from a number, you can use `Array.from({ length: numberOfPlayer })`. It is programmatically more correct than `Array(numberOfPlayer).fill(null)`

2024-07-13 16:39 UTC, LocTran-saritasa requested changes

2024-07-13 16:39 UTC, LocTran-saritasa commented on apps/vanilla/src/pages/black-jack/models/publisher.ts
> +	private subscribers: Subscriber<T>[] = [];
You can use `Set` to ensure that the subscriber is not duplicated
Btw, don't forget to use `readonly`
```ts
private readonly subscriber = new Set<Subscriber<T>>()
```

2024-07-13 16:39 UTC, LocTran-saritasa commented on apps/vanilla/src/pages/black-jack/features/player-displayer.ts
> +		const latestScore = turnResult.at(-1) ?? -1;
I wonder why the `latestScore` is -1 instead of 0 in case you cannot get it from the `turnResult`

2024-07-13 16:39 UTC, LocTran-saritasa commented on apps/vanilla/src/pages/black-jack/features/main.ts
> +	});
Is it possible to do this inside `createPlayers`? then we don't need to loop through the player list here

2024-07-13 16:39 UTC, LocTran-saritasa commented on apps/vanilla/src/pages/black-jack/features/main.ts
> +	const playersCountInput = 6;
`playersCountInput` should be defined like the `DICE_SIDES`

2024-07-13 16:39 UTC, LocTran-saritasa commented on apps/vanilla/src/pages/black-jack/index.css
> +	background: white;
Don't forget to use variable for all of your colors

2024-07-13 16:39 UTC, LocTran-saritasa commented on apps/vanilla/src/pages/black-jack/features/turn-generator.ts
> +		this.currentPlayerIndex = 0;
You don't need to assign the value for `currentPlayerIndex` 2 times

2024-07-13 16:39 UTC, LocTran-saritasa commented on apps/vanilla/src/pages/black-jack/features/turn-generator.ts
> +		});
I believe you don't want to call `this.next()` on each subscriber
It didn't cause error because you only have one subscriber in your `TurnGenerator` at the moment

2024-07-13 16:39 UTC, LocTran-saritasa commented on apps/vanilla/src/pages/black-jack/features/dice-generator.ts
> +		this.getSubcribers()[diceResult.playerIndex].update(diceResult);
You cannot guarantee that the index of the player inside the subscriber list is matched with the index when you create the player. What if the subscriber list got shuffled? Your logic will be broken.
Let's find the player by their index. Ex: `subscribers.find(s => s.index === diceResult.playerIndex)`
Note that to do this, you must store the player index inside the Player instance

2024-07-14 09:02 UTC, kytran-saritasa commented on apps/vanilla/src/pages/black-jack/models/publisher.ts
> +	private subscribers: Subscriber<T>[] = [];
@LocTran-saritasa Nice skill brother, now it is mine 🤣🤣

2024-07-14 09:07 UTC, kytran-saritasa commented on apps/vanilla/src/pages/black-jack/index.css
> +	background: white;
@trinhnguyen-saritasa And use hex value instead of rgb or text name
Look the code example of Naming, instead of using 'black', we use '#000' (same for white): https://wiki.saritasa.rocks/frontend/languages/css#naming

2024-07-15 02:45 UTC, trinhnguyen-saritasa commented on apps/vanilla/src/pages/black-jack/models/publisher.ts
> +	public getSubcribers(): readonly Subscriber<T>[] {
Thank you so much

2024-07-15 07:38 UTC, khoanguyen-saritasa commented on apps/vanilla/src/type-guards/is-element.ts
> +export function isElement(element: HTMLElement | unknown): element is HTMLElement {
It should be `unknown` only.
```suggestion
export function isElement(element: unknown): element is HTMLElement {
```

2024-07-15 07:38 UTC, khoanguyen-saritasa commented on apps/vanilla/src/pages/black-jack/features/win-displayer.ts
> +		}
Let's use early return, your code will be cleaner., without too many nested level.
```suggestion
	public update(isWinner: boolean): void {
	  if(!isWinner){
	      return
	  }
		const playerElement = this.elementContainer.querySelector('ul');
		const rollButton = document.getElementById('roll-dice');
		if (isElement(playerElement) && isButtonElement(rollButton)) {
				playerElement.classList.add('pink');
				rollButton.disabled = true;
		}
```

2024-07-15 07:38 UTC, khoanguyen-saritasa commented on apps/vanilla/src/pages/black-jack/features/turn-generator.ts
> +		this.currentPlayerIndex = 0;
Is this comment  resolved?

2024-07-15 07:38 UTC, khoanguyen-saritasa commented on apps/vanilla/src/pages/black-jack/features/player-displayer.ts
> +		const latestScore = turnResult.at(-1) ?? -1;
Maybe you can simple `return` if void  statement if `latestScore` is `null`.

2024-07-15 07:44 UTC, trinhnguyen-saritasa commented on apps/vanilla/src/pages/black-jack/features/turn-generator.ts
> +		});
Yay, I moved it outside loop.

2024-07-15 11:38 UTC, khoanguyen-saritasa commented on apps/vanilla/src/pages/black-jack/features/dice-generator.ts
> +		}
As I said before, let's use non-strict comparation for `null` and `undefined` value.
```suggestion
		if (currentPlayer != null) {
			currentPlayer.update(playerTurnResult);
		}
```

2024-07-15 11:38 UTC, khoanguyen-saritasa commented on apps/vanilla/src/pages/black-jack/models/player-turn-result.ts
> +	readonly diceResult: number;
Let's add docs instead of disabling the `eslint` rule.

2024-07-15 11:38 UTC, khoanguyen-saritasa commented on apps/vanilla/src/pages/black-jack/features/dice-generator.ts
> +		const currentPlayer = (this.subscriberArr as Player[]).find(s => s.index === playerTurnResult.playerIndex);
Why do we need to perform a typecast here? If you need `subscriberArr` to have it typed as `Player`, you should change the generic type for `Publisher<PlayerTurnResult>` rather than casting type here.

2024-07-16 07:23 UTC, dbitkovski requested changes

2024-07-16 07:23 UTC, dbitkovski commented on apps/vanilla/src/pages/black-jack/features/dice-generator.ts
> +		}
I don't really like that the publisher knows about its subscribers. One of main ideas of the Observer pattern is that we work with abstractions and not implementations. As far as I understand `DiceGenerator` is just a class that roll dices when it's asked. Do you remember about single responsibility principle? A module (function, class, actual module) should have only 1 purpose. In our case `DiceGenerator` generates new result of dice roll and since it's publisher it just notify all subscribers about new result. If you need an instrument to update the result of each user you should think about some kind of game manager. This is the class with more global responsibility because it manages a whole game. So when `DiceGenerator` notifies it's subscribers, this manager gets a new result, pick current player and update it's result

2024-07-16 07:23 UTC, dbitkovski commented on apps/vanilla/src/pages/black-jack/features/dice-generator.ts
> +		}
Imagine that I'm a client and asked you to implement this game. Now I want to see a popup when a user rolls "1" or "6". For example if a user gets "1" we show something fun and if it's "6" we show something cool.
Since your `DiceGenerator` only notifies `Player`, most likely you'll add this logic there. In this case `Player`, which is domain model, knows about some popups and we have responsibility issue again.

This example might look a bit strange but in general this happens all the time :cat:

2024-07-16 07:23 UTC, dbitkovski commented on apps/vanilla/src/pages/black-jack/features/main.ts
> +				}
1. This condition might be placed before `return` statement because you don't need to check it on each iteration
2. I guess `getElementById` return type is something like `HTMLElement | undefined`. When we have nullable type we don't need to write separate type guards, we can come up with a function that checks whether a passed value a null and return correct type. Here is a signature `isNotNull<T>(value: T): value is NonNullable<T>`

2024-07-16 07:23 UTC, dbitkovski commented on apps/vanilla/src/pages/black-jack/features/main.ts
> +			if (isElement(playerElement)) {
Does `createElement` return nullable type? Not sure we need this condition here

2024-07-16 07:23 UTC, dbitkovski commented on apps/vanilla/src/pages/black-jack/features/turn-generator.ts
> +	 * Notify to dice-generator to generate new result for current player.
Again, that's totally fine that different parts of application know about each other but does it really matter here? I mean `TurnGenerator` works perfectly without `DiceGenerator` so why should we specify this in doc?

2024-07-16 07:23 UTC, dbitkovski commented on apps/vanilla/src/type-guards/is-player.ts
> +	return (subscriber as Player).index !== undefined;
`Player` is a class, you can use `instanceof` operator

2024-07-16 07:23 UTC, dbitkovski commented on apps/vanilla/src/pages/black-jack/models/publisher.ts
> +	public get subscriberArr(): readonly Subscriber<T>[] {
1. Usually we don't want other classes to access subscribers list because it doesn't bring any information, let's make it `protected` so only children can get it
2. Change current `private subscribers` to `private _subscribers` and `subscriberArr` to `subscribers`

2024-07-16 07:56 UTC, trinhnguyen-saritasa commented on apps/vanilla/src/pages/black-jack/features/dice-generator.ts
> +		}
Yeah. I changed DiceGenerator generates new result of dice roll and since it's publisher it just notify all subscribers about new result. Then, I filtered the result in each player.

2024-07-16 07:56 UTC, trinhnguyen-saritasa commented on apps/vanilla/src/pages/black-jack/features/main.ts
> +			if (isElement(playerElement)) {
Thank you. I removed check function

2024-07-16 08:03 UTC, trinhnguyen-saritasa commented on apps/vanilla/src/type-guards/is-player.ts
> +	return (subscriber as Player).index !== undefined;
Thank you. I removed this class. Dice Generator notify to all subscriber the result.

2024-07-17 09:23 UTC, khoanguyen-saritasa approved these changes

2024-07-17 09:23 UTC, khoanguyen-saritasa commented on apps/vanilla/src/type-guards/is-player.ts
> +	return (subscriber as Player).index !== undefined;
Do you use it anywhere? If not, you can remove it.

2024-07-17 11:35 UTC, dbitkovski requested changes

2024-07-17 11:35 UTC, dbitkovski commented on apps/vanilla/src/pages/black-jack/features/result-displayer.ts
> +export abstract class ResultDisplayer {
What is the point of this class? It doesn't have any common logic nor used as an abstraction. Let's remove

2024-07-17 11:35 UTC, dbitkovski commented on apps/vanilla/src/type-guards/is-element.ts
> +export function isNotNull<T>(value: T): value is NonNullable<T> {
Update doc and rename the file

2024-07-17 11:35 UTC, dbitkovski commented on apps/vanilla/src/type-guards/is-player.ts
> +	return (subscriber as Player).index !== undefined;
Same about `isButtonElement`

2024-07-17 11:35 UTC, dbitkovski commented on apps/vanilla/src/pages/black-jack/features/player-displayer.ts
> +		const latestScore = turnResult.at(-1) ?? -1;
Don't see any changes here

2024-07-17 14:47 UTC, trinhnguyen-saritasa commented on apps/vanilla/src/type-guards/is-player.ts
> +	return (subscriber as Player).index !== undefined;
Thank you. I removed it.

2024-07-17 15:57 UTC, trinhnguyen-saritasa commented on apps/vanilla/src/type-guards/is-element.ts
> +export function isNotNull<T>(value: T): value is NonNullable<T> {
I created two type-guard: one is to check is HTMLElement, the another is to check HTMLButtonElement. I still remain check HTMLButtonElement because I disable button type when game end. So I separate them.

2024-07-17 15:58 UTC, LocTran-saritasa requested changes
I am not sure but looks like you missed these 4 hidden comments because most of them are not resolved yet. Pls double check :)
![image](https://github.com/user-attachments/assets/64d16c6a-1d15-4863-b49e-9303b674c066)

2024-07-17 15:58 UTC, LocTran-saritasa commented on apps/vanilla/src/pages/black-jack/features/player.ts
> +	public readonly playerIndex: number;
Pls provide docs

2024-07-17 15:58 UTC, LocTran-saritasa commented on apps/vanilla/src/pages/black-jack/features/player.ts
> +	private get getTotalScore(): number {
```suggestion
	private get totalScore(): number {
```

2024-07-17 15:58 UTC, LocTran-saritasa commented on apps/vanilla/src/pages/black-jack/features/turn-generator.ts
> +	public getCurrentPlayerIndex(): number {
```suggestion
	public get currentPlayerIndex(): number {
```

2024-07-17 16:10 UTC, trinhnguyen-saritasa commented on apps/vanilla/src/pages/black-jack/models/publisher.ts
> +	private subscribers: Subscriber<T>[] = [];
I fixed it. I am sorry for missing this require.

2024-07-17 16:31 UTC, trinhnguyen-saritasa commented on apps/vanilla/src/pages/black-jack/features/player-displayer.ts
> +		const latestScore = turnResult.at(-1) ?? -1;
I changed const latestScore = turnResult.at(-1) ?? -1; to const latestScore = turnResult.at(-1) ?? 0; for bad case I cannot get the turnResult according to your request. Thank you.

2024-07-19 08:52 UTC, LocTran-saritasa approved these changes

2024-07-19 08:52 UTC, LocTran-saritasa commented on apps/vanilla/src/pages/black-jack/models/publisher.ts
> +	private _subscribers = new Set<Subscriber<T>>();
```suggestion
	private readonly _subscribers = new Set<Subscriber<T>>();
```

2024-07-19 12:42 UTC, dbitkovski approved these changes

2024-07-23 02:46 UTC, merged