Feature/jc 640 initialize anime app and table view angular
saritasa-nest/camp-js-2024-trinh-nguyen pull request #3
Opened 2024-07-24 10:28 UTC by trinhnguyen-saritasa

Feature/jc 640 initialize anime app and table view angular: This is an anime topic website that call api from back-end. This stage is initialized a dashboard contains an anime table display anime list.

2024-07-25 05:44 UTC, artem-sotnichenko-saritasa commented
@trinhnguyen-saritasa Please fix "Deploy PR previews" job failing

2024-07-26 05:10 UTC, andrey-gazzaev requested changes
![image](https://github.com/user-attachments/assets/b72025f8-e005-42ca-a371-71bd96e1e599)
If you quickly switch pages, you can go into a negative value

2024-07-26 05:10 UTC, andrey-gazzaev commented on apps/angular/src/core/pipes/no-empty.pipe.ts
> +	name: 'noEmpty',
Why `noEmpty`? After all, your pipe works with **empty** values

2024-07-26 05:10 UTC, andrey-gazzaev commented on apps/angular/src/core/pipes/no-empty.pipe.ts
> +		return value != null && (value !== '' || typeof value === 'number' && !isNaN(value)) ? value : NULL_VALUE;
```suggestion
		return value != null && (value !== '' || typeof value === 'number' && !isNaN(value)) ? value : NULL_VALUE;
```
Let's turn your ninja code into readable code.

2024-07-26 05:10 UTC, andrey-gazzaev commented on apps/angular/src/core/services/anime.service.ts
> +			.set('offset', (options.pageNumber * ITEM_PER_PAGE).toString());
Let's make a mapper for this

2024-07-26 10:50 UTC, maxineo requested changes
I think your anime models, enums, mappers, etc are not app specific, so there is no reason to put them into angular app and you can move them into `core` library.

2024-07-26 10:50 UTC, maxineo commented on apps/angular/src/app/features/dashboard/anime-table/anime-table.component.ts
> +	/** Receive observable include pagination type of Anime api. */
```suggestion
	/** Anime list. */
```

2024-07-26 10:50 UTC, maxineo commented on apps/angular/src/app/features/dashboard/anime-table/anime-table.component.ts
> +	/**  Notify newest index page to user who subscribe it when user click next/previous page. */
You try to describe too much details. Just describe what this variables stores(in case of observables what values are emited), not how the consumer should use it.

2024-07-26 10:50 UTC, maxineo commented on apps/angular/src/app/features/dashboard/dashboard.component.html
> +<camp-anime-table></camp-anime-table>
```suggestion
<camp-anime-table />
```

2024-07-26 10:50 UTC, maxineo commented on apps/angular/src/core/dtos/anime-status.dto.ts
> +/** List of anime status. */
This is not a list, this is enum. We usually just describe what enum represents. Please check other enums as well.
```suggestion
/** Anime status DTO. */
```

2024-07-26 10:50 UTC, maxineo commented on apps/angular/src/core/mappers/anime.mapper.ts
> +const statusMappingFromDto: Record<AnimeStatusDto, AnimeStatus> = {
You should use capitalized snake case for constants. Also dont forget about `readonly`.
```suggestion
const STATUS_FROM_DTO: Readonly<Record<AnimeStatusDto, AnimeStatus>> = {
```

2024-07-26 10:50 UTC, maxineo commented on apps/angular/src/core/models/anime.ts
> +	public readonly genres: readonly number[];
```suggestion
	/** Studio IDs. */
	public readonly studioIDs: readonly number[];

	/** Genre IDs. */
	public readonly genreIDs: readonly number[];
```

2024-07-26 10:50 UTC, maxineo commented on apps/angular/src/core/services/anime.service.ts
> +		const url = new URL('anime/anime/', this.baseUrl);
I suggest you to create a service to work with urls. That way you can reuse them and easily modify if needed.

2024-07-26 10:50 UTC, maxineo commented on libs/core/mappers/imapper.ts
> +export type IMapperToDto<TDto, TDomain> = {
We dont use `I` prefix anymore.

2024-07-26 10:50 UTC, maxineo commented on libs/core/mappers/imapper.ts
> +	 */
```suggestion
	/**
	 * Maps from DTO to Domain model.
	 * @param dto DTO.
	 */
```

2024-07-26 10:50 UTC, maxineo commented on libs/core/mappers/imapper.ts
> +/** Mapper type helps convert from Domain Model to Dto Model. */
There is no `DTO model`, there is just `DTO`.

2024-07-26 10:50 UTC, maxineo commented on libs/core/mappers/pagination.mapper.ts
> + */
Please remove dead code.

2024-07-26 10:50 UTC, maxineo commented on libs/core/models/pagination.dto.ts
Please remove `dto` from the filename

2024-07-26 10:50 UTC, maxineo commented on libs/core/models/pagination.dto.ts
> +/** T type information of each fetch. */
Your models shouldnt know anything about fetching.
```suggestion
/** Pagination. */
```

2024-07-26 10:50 UTC, maxineo commented on libs/core/utils/response-with-pagination.utils.ts
> +export type ResponseWithPaginationDto<T> = {
Is it used somewhere? Im not sure why do you need that. You used just `PaginationDto` in pagination mapper.

2024-07-26 10:50 UTC, maxineo commented on libs/core/mappers/pagination.mapper.ts
> +			hasPrev: Boolean(paginationDto.previous),
```suggestion
			hasNext: paginationDto.next !== null,
			hasPrev: paginationDto.previous !== null,
```

2024-07-30 05:01 UTC, trinhnguyen-saritasa commented on apps/angular/src/app/app.routes.ts
> +		component: DashboardComponent,
Thank you so much for this suggestion.

2024-07-30 05:06 UTC, trinhnguyen-saritasa commented on apps/angular/src/app/features/dashboard/anime-table/anime-table.component.css
> +	background-color: #9e9e9e33;
Thank you so much. Yeah, Sometimes, I confused about TODO comments I had left after even short time. I will improve TODO comment as this.

2024-07-30 07:51 UTC, trinhnguyen-saritasa commented on apps/angular/src/app/features/dashboard/anime-table/anime-table.component.ts
> +	private readonly pageSubject$ = new BehaviorSubject<number>(this.currentPage);
I changed this variable. It contains 2 value: page Index and page size.

2024-08-01 03:42 UTC, andrey-gazzaev approved these changes

2024-08-01 03:42 UTC, andrey-gazzaev commented on apps/angular/src/app/features/dashboard/anime-table/anime-table.component.html
> +	></mat-paginator>
```suggestion
	<mat-paginator
	[pageSizeOptions]="[5, 10, 20]"
	[length]="animeList.totalCount"
	[pageIndex]="pageSubject$.value.pageIndex"
	[pageSize]="pageSubject$.value.pageSize"
	(page)="getPaginatorData($event)"
	/>
```

2024-08-01 03:42 UTC, andrey-gazzaev commented on apps/angular/src/app/features/dashboard/anime-table/anime-table.component.ts
> +	protected getPaginatorData(event: PageEvent): void {
```suggestion
	protected onPaginationChange(event: PageEvent): void {
```

2024-08-01 03:42 UTC, andrey-gazzaev commented on apps/angular/src/app/features/dashboard/anime-table/anime-table.component.ts
> +	protected readonly pageSubject$ = new BehaviorSubject<PageEvent>({ pageSize: ITEM_PER_PAGE, pageIndex: PAGE_DEFAULT });
```suggestion
	protected readonly pagination$ = new BehaviorSubject<PageEvent>({ pageSize: ITEM_PER_PAGE, pageIndex: PAGE_DEFAULT });
```

2024-08-01 03:42 UTC, andrey-gazzaev commented on apps/angular/src/app/features/dashboard/anime-table/anime-table.component.ts
> +	protected getPaginatorData(event: PageEvent): void {
https://wiki.saritasa.rocks/frontend/languages/ts-js/naming#on

2024-08-01 03:42 UTC, andrey-gazzaev commented on apps/angular/src/app/features/dashboard/anime-table/anime-table.component.ts
> +	protected trackByFn(index: number, item: Anime): number {
```suggestion
	protected trackByAnimeId(index: number, item: Anime): number {
```

2024-08-01 03:42 UTC, andrey-gazzaev commented on apps/angular/src/core/services/anime.service.ts
> +	public getAnime(model: AnimeParams): Observable<Pagination<Anime>> {
```suggestion
	public getList(model: AnimeParams): Observable<Pagination<Anime>> {
```

If the name of the entity and the service coincide, you can resort to an abstract name

2024-08-01 03:42 UTC, andrey-gazzaev commented on libs/core/dtos/anime-params.dto.ts
> +export type AnimeParamsDto = Readonly<{
```suggestion
export type AnimePaginationDto = Readonly<{
```
This is too abstract a name for the structure.

2024-08-01 03:42 UTC, andrey-gazzaev commented on libs/core/dtos/anime.dto.ts
> +};
```suggestion
/** Anime DTO. */
export type AnimeDto = Readonly<{

	/** ID. */
	id: number;

  //...
}>;
```

2024-08-01 20:11 UTC, maxineo commented on libs/core/enums/animeTableColumns.ts
> +}
```suggestion
export enum AnimeTableColumns {
	IMAGE = 'Image',
	TITLE_EN = 'English title',
	TITLE_JPN = 'Japanese title',
	AIRED_START = 'Aired start date',
	TYPE = 'Type',
	STATUS = 'Status',
}
```

2024-08-01 20:11 UTC, maxineo commented on libs/core/enums/apiPath.ts
> +}
```suggestion
export enum ApiPaths {
	anime = 'anime/anime/',
}
```

2024-08-01 20:11 UTC, maxineo commented on libs/core/mappers/anime.mapper.ts
> +/** Anime mapper map Model to Dto and vice vera Dto to Model. */
It can also map other things if necessary
```suggestion
/** Anime mapper. */
```

2024-08-01 20:11 UTC, maxineo commented on libs/core/models/anime.ts
> +import { DateTimeRange } from './datetime-range';
Please keep an eye on imports. Make sure there are no unnecessary empty lines
```suggestion
import { AnimeStatus } from './anime-status';
import { AnimeType } from './anime-type';
import { DateTimeRange } from './datetime-range';
```

2024-08-01 20:11 UTC, maxineo commented on libs/core/models/anime.ts
> +	readonly genres: readonly number[];
```suggestion
	readonly studioIds: readonly number[];

	/** Genre IDs. */
	readonly genreIds: readonly number[];
```

2024-08-01 20:11 UTC, maxineo commented on libs/core/pipes/no-empty.pipe.ts
> +	name: 'TransferEmpty',
Lets also rename file name and class name.

2024-08-01 20:11 UTC, maxineo commented on libs/core/records/status-from-dto.ts
> +export const statusMappingFromDto: Readonly<Record<AnimeStatusDto, AnimeStatus>> = {
For consistency I suggest you to create an actual mapper for it.

2024-08-01 20:11 UTC, maxineo approved these changes

2024-08-02 13:11 UTC, dbitkovski approved these changes

2024-08-02 13:11 UTC, dbitkovski commented on apps/angular/src/app/features/dashboard/anime-table/anime-table.component.ts
> +	protected trackByFn(index: number, item: Anime): number {
I'd recomment name the function `trackAnime` because this is literally what it does.
- `trackByAnimeId` described internal implementation which is necessary 
- `trackByAnimeId` doesn't specify what we track

Eventually, `[trackBy]="trackAnime()"` looks fine and easy to understand

2024-08-02 13:11 UTC, dbitkovski commented on apps/angular/src/app/features/dashboard/anime-table/anime-table.component.ts
> +	 * Function return index of item in an array.
You don't need to describe what happens inside the function. Also, it doesn't return index, it returns anime id :)

2024-08-02 13:11 UTC, dbitkovski commented on libs/theme/src/variables.css
> +	/* space */
I see you also defined the same variables here `apps/angular/src/theme/variable.css`. Could you remove them in one of those files?

2024-08-05 06:35 UTC, trinhnguyen-saritasa commented on libs/core/records/status-from-dto.ts
> +export const statusMappingFromDto: Readonly<Record<AnimeStatusDto, AnimeStatus>> = {
Thank you for your suggestion.

2024-08-05 06:42 UTC, merged